import assert from 'node:assert/strict';
import {Engine} from '../dist/engine.js';
import {freeze} from '../dist/combo.js';
import {castAscension,updateAscension,moveAscension,enemyAttackFactor,moveIca} from '../dist/ascension-combat.js';
import {updateHazard} from '../dist/trial.js';
import {drawAscension,drawAscensionWave} from '../dist/expansion-render.js';
const setup=(ids)=>{const e=new Engine(()=>.99);e.quest=3;e.travel('starfield');e.team=ids;e.updateSpawns=()=>{};e.giveXP=()=>{};e.enemies=[];e.modal=null;Object.assign(e.hero,{x:2350,y:1700,inv:999});for(const m of Object.values(e.members))Object.assign(m,{x:2350,y:1700,cd:0});return e;};
const foe=(e,x=2800,y=1700,hp=1e6,boss=false)=>{const a={id:'test'+e.enemies.length,x,y,homeX:x,homeY:y,hp,maxHp:hp,r:18,kind:'melee',frozen:0,slow:1000,dot:0,cd:999,damageScale:1,boss};e.enemies.push(a);if(boss)e.bossAwake=true;return a;};
const run=(e,t)=>{for(let i=0;i<t*50;i++){e.update(.02);e.modal=null;}};
for(const id of [15,16,17,20,21,22,23]){const e=setup([id]),a=foe(e);run(e,1.5);assert.ok(e.stats.skills[id]>0,id+' attacks without touching enemy');assert.ok(a.hp<1e6,id+' projectile damages enemy');if([15,16,17,22,23].includes(id))assert.ok(Math.abs(e.members[id].x-2350)<25,id+' stands in casting position');}
for(const id of [15,16,17,20,21,22,23]){const e=setup([id]);foe(e,3250);run(e,2);assert.equal(e.combat,false);assert.equal(e.stats.skills[id]||0,0,'no precombat casts');assert.equal(e.projectiles.length,0);assert.equal(e.ascFields.length,0);}
{const e=setup([15]);foe(e,2750);const far=foe(e,3750);run(e,3);assert.ok(far.hp<1e6,'ice blade travels beyond activation range');}
{const e=setup([16]);const a=foe(e);e.combat=true;castAscension(e,e.members[16],a);assert.equal(e.projectiles.length,8);assert.equal(new Set(e.projectiles.map(p=>Math.atan2(p.ty-p.y,p.tx-p.x).toFixed(2))).size,8);e.members[16].growth={lotus:2};e.damage(a,a.hp,'#fff',{owner:11});assert.equal(e.members[16].deathBuff,1,'another character kill grants Blade soul');}
{const e=setup([22]);const a=foe(e,2700);run(e,.04);e.members[22].cd=99;run(e,2);assert.ok(a.hp<1e6-e.skillData(22).damage,'one tornado hits repeatedly');}
{const e=setup([15]);const m=e.members[15],a=foe(e);e.combat=true;m.growth={mirror:1,eclipse:1};m.moon=8;updateAscension(e,.01);assert.ok(m.rageUntil>e.time);moveAscension(e,m,.01);assert.ok(m.lift>35);const until=m.rageUntil;e.time+=.5;freeze(e,a,2);updateAscension(e,.01);assert.ok(m.rageUntil>until,'freeze extends rage');m.growth={execution:1};a.frozen=3;e.companionHit(a,1,e.skillData(15));assert.ok(a.hp<=0);const boss=foe(e,2800,1700,1e6,true);boss.frozen=3;e.companionHit(boss,1,e.skillData(15));assert.ok(boss.hp>999900,'boss not executed');}
{const e=setup([17,1]);const m=e.members[17],a=foe(e),b=foe(e,2950);e.combat=true;m.growth={dragon:1,lotus:1,twin:1};m.dragon=7;e.damage(a,1,'#fff',{owner:1});assert.equal(m.dragon,8);updateAscension(e,.02);assert.ok(e.ascFields.some(f=>f.style==='vortex'));assert.ok(e.ascFields.some(f=>f.style==='waterColumn'));assert.ok(m.ascRun);const before=Math.abs(b.x-a.x);updateAscension(e,.2);assert.ok(Math.abs(b.x-a.x)<before);const pos={x:m.x,y:m.y};moveAscension(e,m,.1);assert.ok(Math.hypot(m.x-pos.x,m.y-pos.y)>25);}
{const e=setup([20]);const m=e.members[20],normal=foe(e),abnormal=foe(e,2860),boss=foe(e,2900,1700,1e6,true);normal.slow=0;abnormal.frozen=2;boss.frozen=2;e.combat=true;m.growth={unsheathe:1,red:1};m.dream=10;updateAscension(e,.02);assert.ok(abnormal.hp<=0);assert.ok(normal.hp>0);assert.ok(boss.hp>0&&boss.hp<1e6);assert.ok(m.whiteUntil>e.time);castAscension(e,m,boss);assert.ok(m.cd<.5);}
{const e=setup([22,21]);const m=e.members[21],a=foe(e);e.combat=true;m.growth={superbreak:1};e.members[22].growth={gunblade:1};e.companionHit(a,1,e.skillData(22));assert.ok(a.broken>0);assert.equal(enemyAttackFactor(a),.65);e.companionHit(a,1,e.skillData(21));assert.ok(a.hp<=0);const b=foe(e,2800,1700,1e6,true);b.broken=3;e.companionHit(b,1,e.skillData(21));assert.ok(b.hp>0);let damage=0;e.hurt=n=>damage=n;updateHazard(e,{kind:'warning',shape:'circle',x:e.hero.x,y:e.hero.y,r:99,life:0,hitDamage:100,host:b});assert.equal(damage,65,'broken reduces boss hazard damage');}
{const e=setup([23,1]);const m=e.members[23],a=foe(e),b=foe(e,2980),far=foe(e,4500);e.combat=true;m.growth={page:1,shatter:1};updateAscension(e,.02);assert.ok(far.frozen>0,'global gold freeze');e.damage(a,50,'#fff',{owner:1});for(let i=0;i<10;i++){e.time+=.1;updateAscension(e,.1);}assert.ok(b.hp<1e6,'damage spreads between enemies');assert.ok(b.frozen>0);assert.ok(e.ascSpread.length<=96);}
{const e=setup([24]);const m=e.members[24],a=foe(e,2650),p={id:26,owner:24,x:2350,y:1700};e.combat=true;m.growth={flight:2};for(let i=0;i<120;i++){e.time+=.02;moveIca(e,p,m,.02);}assert.ok(a.hp<1e6);assert.ok(p.x>2800||p.rush?.left<4,'pony traverses battle');}
{const e=setup([15,17,20,22]);foe(e);e.combat=true;e.members[17].dragon=12;e.members[17].growth={dragon:2,twin:2};updateAscension(e,.02);e.setModal('pause');const t=e.time,life=e.ascFields[0].life;e.update(2);assert.equal(e.time,t);assert.equal(e.ascFields[0].life,life);e.modal=null;e.travel('meadow');assert.equal(e.ascFields.length,0);assert.equal(e.members[17].ascRun,null);assert.equal(e.members[17].growth.dragon,2);}
{const e=setup([17]);foe(e);e.combat=true;e.members[17].growth={dragon:1};e.members[17].dragon=8;updateAscension(e,.02);const c=new Proxy({},{get:(o,k)=>o[k]||((...args)=>args.forEach(n=>{if(typeof n==='number')assert.ok(Number.isFinite(n));})),set:(o,k,v)=>(o[k]=v,true)});const at=(x,y,z,f)=>f();at.point=(x,y)=>({x,y});drawAscension(e,c,at);for(const newStyle of ['water','ice','void','blood','tornado'])drawAscensionWave(c,{newStyle,r:50,color:'#fff'},2);}
console.log('Ascension: ranged basics, distant projectiles, no precombat fire, charges, transformations, repeated hits, freeze/spread, break/execute/boss protections, pony, pause and travel passed.');
