import assert from 'node:assert/strict';
import {Engine} from '../dist/engine.js';
import {GROWTH_CARDS,cardsFor} from '../dist/growth.js';
import {renderGrowthTags} from '../dist/growth-tags.js';
import {queueAirstrike,updateFirefly,drawFirefly} from '../dist/firefly-combat.js';
import {readFileSync} from 'node:fs';
const setup=(growth={})=>{const e=new Engine(()=>.99);e.quest=3;e.travel('starfield');e.team=[21];e.updateSpawns=()=>{};e.giveXP=()=>{};e.enemies=[];Object.assign(e.hero,{x:2350,y:1700,inv:999});Object.assign(e.members[21],{x:2350,y:1700,cd:0,growth});return e;};
const foe=(e,x,y,hp=1e6,boss=false)=>{const a={id:'f'+e.enemies.length,x,y,homeX:x,homeY:y,hp,maxHp:hp,r:17,cd:999,kind:'melee',frozen:999,slow:0,dot:0,boss};e.enemies.push(a);if(boss)e.bossAwake=true;return a;};
const run=(e,t)=>{let peak=0;for(let i=0;i<t*50;i++){e.update(.02);e.modal=null;peak=Math.max(peak,e.fireflyBombs?.length||0);for(const a of e.enemies)assert.ok(Number.isFinite(a.hp));}assert.ok(peak<=48);return e;};
const benchmark=growth=>{const e=setup(growth);for(let i=0;i<30;i++)foe(e,2700+i%6*90,1480+Math.floor(i/6)*100);run(e,10);return {damage:e.enemies.reduce((s,a)=>s+Math.min(a.maxHp,a.maxHp-a.hp),0),kills:e.kills};};
const base=benchmark({}),strafe=benchmark({combustion:1}),cluster=benchmark({firefall:1}),execute=benchmark({superbreak:1});assert.ok(base.damage>7772.4*4,'substantially more AoE than previous baseline');assert.ok(strafe.damage>base.damage*1.15);assert.ok(cluster.damage>base.damage*1.4);assert.equal(execute.kills,30,'execute branch reaches the whole clustered formation');console.log({base,strafe,cluster,execute});
{const e=setup({firefall:3,combustion:3});foe(e,2800,1700);run(e,.08);assert.ok(e.members[21].leap);const pending=e.fireflyBombs.length;e.setModal('pause');const t=e.time;e.update(3);assert.equal(e.time,t);assert.equal(e.fireflyBombs.length,pending);e.modal=null;run(e,3);assert.ok(e.members[21].ascRun?.style==='fire'||e.members[21].leap);e.travel('meadow');assert.equal(e.fireflyBombs.length,0);assert.equal(e.members[21].growth.firefall,3);}
{const e=setup({superbreak:3});e.combat=true;const boss=foe(e,2500,1700,1e8,true),sleep=foe(e,2500,1700,1e8,true);e.bossAwake=false;boss.boss=false;boss.broken=3;queueAirstrike(e,boss,10,300,0);updateFirefly(e,.01);assert.equal(sleep.hp,1e8);boss.hp=boss.maxHp;boss.boss=true;e.bossAwake=true;queueAirstrike(e,boss,10,300,0);updateFirefly(e,.01);assert.ok(boss.hp>0&&boss.hp<boss.maxHp);}
{const e=setup({firefall:3,combustion:3,superbreak:3});foe(e,4000,1700);run(e,2);assert.equal(e.combat,false);assert.equal(e.fireflyBombs.length,0);e.combat=true;queueAirstrike(e,e.hero,10,300);e.team=[];updateFirefly(e,.01);assert.equal(e.fireflyBombs.length,0);}
{const e=setup();e.combat=true;foe(e,2600,1700);for(let i=0;i<100;i++)queueAirstrike(e,e.hero,10,100,.2);assert.equal(e.fireflyBombs.length,48);let ops=0;const c=new Proxy({},{get:(o,k)=>o[k]||((...args)=>{ops++;args.forEach(n=>{if(typeof n==='number')assert.ok(Number.isFinite(n));});}),set:(o,k,v)=>(o[k]=v,true)});drawFirefly(e,c,(x,y,z,fn)=>fn());assert.ok(ops>20);}
const gold=GROWTH_CARDS.filter(c=>c.gold);assert.equal(gold.length,70);for(const card of gold){assert.ok(card.tags.length>=2&&card.tags.length<=4,card.id);assert.equal(new Set(card.tags).size,card.tags.length);const html=renderGrowthTags(card);for(const tag of card.tags)assert.ok(html.includes(tag));}for(const card of GROWTH_CARDS.filter(c=>!c.gold))assert.equal(renderGrowthTags(card),'');assert.ok(cardsFor(21).find(c=>c.key==='superbreak').tags.includes('斩杀'));assert.ok(cardsFor(17).find(c=>c.key==='dragon').tags.includes('聚集'));for(const path of ['dist/ui.js','dist/details.js'])assert.ok(readFileSync(new URL('../'+path,import.meta.url),'utf8').includes('${renderGrowthTags(card)}'));
console.log('Firefly branches improve crowd damage; airborne attacks, chain bounds, pause/travel/swap, sleeping/awake boss protection and all 70 gold card tags passed.');
