import {updateGold} from '../dist/gold-combat.js';
import assert from 'node:assert/strict';
import {Engine} from '../dist/engine.js';
import {GROWTH_CARDS,cardsFor,eligible,rollGrowth,grantGrowth,rank} from '../dist/growth.js';
import {heroGrowth,projectileImpact,impactField} from '../dist/growth-combat.js';
import {xpForLevel,companionXP} from '../dist/balance.js';
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('✓ '+name);};
const foe=(x=1300,y=650)=>({id:Math.random(),x,y,homeX:x,homeY:y,hp:1e6,maxHp:1e6,r:16,cd:100,frozen:0,dot:0,slow:0,kind:'melee'});
function scene(id){const e=new Engine(()=>.4);e.team=id?[id]:[];Object.assign(e.hero,{x:1300,y:650,hp:30,inv:100});if(id)Object.assign(e.members[id],{x:1280,y:650});e.enemies=Array.from({length:14},(_,i)=>foe(1300+i*7,650));e.combat=true;return e;}
function card(id,key){return cardsFor(id).find(c=>c.key===key);}
function add(e,id,key,n=1){for(let i=0;i<n;i++)assert.equal(grantGrowth(e,card(id,key)),true);}
test('21 companions each have exactly five ordinary, three gold; hero has extra builds, distinct cards and three descriptions',()=>{assert.equal(GROWTH_CARDS.length,186);assert.equal(new Set(GROWTH_CARDS.map(c=>c.id)).size,186);for(let id=1;id<12;id++){const pool=cardsFor(id);assert.equal(pool.filter(c=>c.gold).length,3);assert.equal(pool.filter(c=>!c.gold).length,5);for(const c of pool)for(let r=1;r<=3;r++)assert.ok(c.describe(r).length>8);}});
test('hero left slot and only equipped companion pool, no duplicates in offer',()=>{const e=new Engine();e.team=[2,7,11];for(let i=0;i<300;i++){const offer=rollGrowth(e,0);assert.equal(offer[0].owner,0);assert.ok(offer.slice(1).every(c=>e.team.includes(c.owner)));assert.equal(new Set(offer.map(c=>c.id)).size,3);}for(let id=1;id<=11;id++)assert.ok(rollGrowth(e,id).every(c=>c.owner===id));});
test('rank III is excluded, repeat grant rejected, choices never reset at team swap or travel',()=>{const e=new Engine();add(e,1,'volley',3);assert.equal(grantGrowth(e,card(1,'volley')),false);assert.ok(!eligible(e,1).some(c=>c.key==='volley'));e.equip(1);assert.ok(rollGrowth(e,0).slice(1).every(c=>c.owner!==1));e.equip(1);assert.equal(rank(e.members[1],'volley'),3);e.quest=3;assert.equal(e.travel('starfield'),true);assert.equal(rank(e.members[1],'volley'),3);e.travel('meadow');});
test('tenth kill triggers hero only; companion starts at twelve kills; curves and cap',()=>{const e=new Engine();e.giveXP(90);assert.equal(e.hero.level,1);e.giveXP(10);assert.equal(e.hero.level,2);assert.equal(e.upgrades.length,1);while(e.upgrades.length)e.chooseUpgrade(0);e.giveXP(20);assert.equal(e.members[1].level,2);assert.equal(companionXP(1),120);assert.equal(companionXP(7),480);for(let n=2;n<=10;n++)assert.ok(xpForLevel(n)>xpForLevel(n-1));assert.equal(xpForLevel(25),3000);assert.equal(xpForLevel(26),6000);e.giveXP(10000);assert.ok(e.hero.level>8);for(const id of e.team){assert.equal(e.members[id].level,8);assert.equal(e.members[id].xp,0);}assert.equal(e.upgrades.filter(u=>u.id===1).length,0);});
test('offer stays stable while paused, each choice is applied exactly once and queued modal resumes',()=>{const e=new Engine();e.giveXP(220);assert.equal(e.upgrades.length,2);const first=e.upgrades[0].choices,selected=first[0];const t=e.time;e.update(1,{right:true});assert.equal(e.time,t);e.nextUpgrade();assert.equal(e.upgrades[0].choices,first);assert.equal(e.chooseUpgrade(9),false);e.pendingWarp=true;let count=0;while(e.upgrades.length){if(e.modal==='warp')e.close();assert.equal(e.modal,'upgrade');e.chooseUpgrade(0);count++;assert.ok(count<50);}assert.equal(count,2);assert.ok(rank(e.hero,selected.key)>0);assert.equal(e.modal,null);});
test('fully mastered and empty team pools convert level rewards to tickets without a modal',()=>{const e=new Engine();for(const c of GROWTH_CARDS)for(let i=0;i<3;i++)grantGrowth(e,c);e.team=[];assert.deepEqual(rollGrowth(e,0),[]);assert.deepEqual(rollGrowth(e,1),[]);const tickets=e.tickets;e.giveXP(100);assert.equal(e.tickets,tickets+1);assert.equal(e.modal,null);});
test('hero sword hits on contact with per-enemy cooldown, bullets hit and poison slows',()=>{const e=scene(0);add(e,0,'sword');e.enemies=[foe(1382,650)];heroGrowth(e,.01);assert.ok(e.enemies[0].hp<1e6);const hp=e.enemies[0].hp;heroGrowth(e,.01);assert.equal(e.enemies[0].hp,hp);add(e,0,'bullet');e.hero.direction=2;heroGrowth(e,1);assert.ok(e.projectiles.some(p=>p.kind==='heroBullet'));add(e,0,'poison');e.hero.moving=true;heroGrowth(e,1);assert.ok(e.zones.some(z=>z.kind==='poison'&&z.slow));e.enemies=[foe(1300,650)];e.update(.033);for(let i=0;i<15;i++)e.update(.033);assert.ok(e.enemies[0].slow>0);assert.ok(e.enemies[0].hp<1e6);});
test('all hero gold cards unlock independent mechanisms and stack',()=>{for(const key of ['swordStorm','bulletNova','toxicBloom']){const e=scene(0);add(e,0,key,3);heroGrowth(e,.02);if(key==='swordStorm')assert.equal(e.orbitSwords.length,7);if(key==='bulletNova'){e.combat=true;updateGold(e,.02);assert.equal(e.projectiles.length,0);assert.ok(e.goldEffects.some(f=>f.key==='bulletNova'&&f.kind==='rain'));}if(key==='toxicBloom'){e.combat=true;updateGold(e,.02);assert.equal(e.zones.length,0);assert.ok(e.projectiles.some(p=>p.poisonDPS>0));};}});
test('ordinary potency, haste and range stack three times for every companion',()=>{for(let id=1;id<12;id++){const e=scene(id),base=e.skillData(id);for(const k of ['power','haste','range'])add(e,id,k,3);const c=e.skillData(id);assert.ok(c.strength>base.strength);assert.ok(c.cd<base.cd);assert.ok(c.range>base.range);}});
test('March gold volley, freeze blast and replenishing shield each affect battle',()=>{for(const key of ['volley','iceBurst','iceShield']){const e=scene(1);add(e,1,key,3);e.cast(e.members[1],e.enemies[0]);if(key==='volley')assert.equal(e.projectiles.length,7);if(key==='iceShield')assert.equal(e.hero.shield,18);if(key==='iceBurst'){e.combat=true;updateGold(e,.02);assert.ok(e.projectiles.some(p=>p.kind==='fanArrow'&&p.pierces===2));}}});
test('Dan Heng and Seele combo, AoE, wake and kill reprise work',()=>{for(const [id,key] of [[2,'combo'],[2,'windBurst'],[2,'windWake'],[11,'combo'],[11,'reprise'],[11,'quantum']]){const e=scene(id);add(e,id,key,3);if(key==='reprise')e.enemies[0].hp=1;e.cast(e.members[id],e.enemies[0]);if(key==='combo')assert.ok(e.fx.filter(f=>f.kind==='slash'||f.kind==='scythe').length>=7);if(key==='windBurst')assert.equal(e.projectiles.filter(p=>p.windBlade).length,16);if(key==='quantum')assert.ok(e.projectiles.some(p=>p.kind==='bladeWave'));if(key==='windWake')assert.ok(e.zones.length);if(key==='reprise')assert.ok(e.members[id].cd<.2);}});
test('Himeko and Jing Yuan barrages, huge impacts and aftershocks work',()=>{for(const id of [3,8])for(const key of ['barrage','solar','aftershock']){const e=scene(id);add(e,id,key,3);e.cast(e.members[id],e.enemies[0]);const impacts=e.fx.filter(f=>f.skill);if(key==='barrage')assert.equal(impacts.length,id===8?7:4);if(key==='solar'){assert.ok(impacts[0].r>150);assert.ok(impacts[0].damage>100);}if(key==='aftershock'){assert.equal(impacts.length,2);assert.equal(impacts[1].delay,.6);}impactField(e,impacts[0]);assert.ok(e.enemies[1].hp<1e6);}});
test('Herta gold spin, blast and direct freeze work',()=>{for(const key of ['combo','iceBurst','frostWake']){const e=scene(4);add(e,4,key,3);e.cast(e.members[4],e.enemies[0]);if(key==='combo'){assert.equal(e.fx.filter(f=>f.kind==='spin').length,4);assert.ok(e.members[4].spin>0);}if(key==='iceBurst')assert.ok(e.fx.some(f=>f.kind==='burst'));if(key==='frostWake'){assert.ok(e.enemies.some(a=>a.frozen>0));assert.equal(e.zones.length,0);}}});
test('Gepard fortress, blast and team cooldown reduction work',()=>{for(const key of ['fortress','iceBurst','rally']){const e=scene(5);e.team=[5,1];e.members[1].cd=5;add(e,5,key,3);e.cast(e.members[5],e.enemies[0]);if(key==='fortress'){assert.ok(e.hero.shield>100);assert.ok(e.enemies[0].frozen>0);}if(key==='iceBurst')assert.ok(e.enemies[1].hp<999900);if(key==='rally')assert.ok(e.members[1].cd<3);}});
test('Natasha overheal, team cooldown and offensive medicine work even at full life',()=>{for(const key of ['overheal','rally','medicine']){const e=scene(6);e.hero.hp=100;e.members[6].cd=0;e.team=[6,1];e.members[1].cd=5;add(e,6,key,3);e.update(.01);assert.ok(e.stats.skills[6]>0);if(key==='overheal')assert.ok(e.hero.shield>60);if(key==='rally')assert.ok(e.members[1].cd<3);if(key==='medicine')assert.equal(e.projectiles.filter(p=>p.medicine).length,5);}});
test('Kafka additional chains, dot detonation and thunder splash work',()=>{for(const key of ['chain','detonate','thunder']){const e=scene(7);add(e,7,key,3);e.cast(e.members[7],e.enemies[0]);if(key==='chain')assert.equal(e.fx.filter(f=>f.kind==='lightning').length,12);if(key==='detonate')assert.ok(e.enemies[0].hp<999940);if(key==='thunder')assert.ok(e.enemies[8].hp<1e6);}});
test('Clara multi-robot, missiles and explosions and Asta volleys, explosions, rally work',()=>{for(const [id,key] of [[9,'robots'],[9,'missiles'],[9,'explosive'],[10,'volley'],[10,'explosive'],[10,'rally']]){const e=scene(id);add(e,id,key,3);e.team=[id,1];e.members[1].cd=5;e.cast(e.members[id],e.enemies[0]);if(key==='robots')assert.equal(e.summons.length,4);if(key==='missiles'){let launched=0;const fire=e.fire.bind(e);e.fire=(a,t,c,d)=>{if(c.kind==='missile')launched++;fire(a,t,c,d);};for(let i=0;i<5;i++)e.update(.033);assert.equal(launched,7);}if(key==='volley')assert.equal(e.projectiles.length,12);if(key==='rally')assert.equal(e.members[1].cd,3.5);if(key==='explosive'){if(id===9)e.fire(e.summons[0],e.enemies[0],{...e.summons[0].c,kind:'missile'});projectileImpact(e,e.enemies[0],e.projectiles[0]);assert.ok(e.enemies[1].hp<1e6);}}});
test('March shield replenishment preserves a stronger existing shield',()=>{const e=scene(1);add(e,1,'iceShield',3);e.hero.shield=300;e.cast(e.members[1],e.enemies[0]);assert.equal(e.hero.shield,300);});
console.log(`${checks} growth system checks passed.`);
