import assert from 'node:assert/strict';
import {Engine} from '../dist/engine.js';
import {CHARS} from '../dist/data.js';
import {cardsFor,eligible,growthOwners,rollGrowth,rollGold} from '../dist/growth.js';
import {xpForLevel,TRIAL_TICKET_CAP} from '../dist/balance.js';
const max=(e,id)=>{(id?e.members[id]:e.hero).growth=Object.fromEntries(cardsFor(id).map(c=>[c.key,3]));};
{const e=new Engine(()=>.99);e.owned=[1,2,3,4,5,6];e.team=[...e.owned];e.pickupTicket();const c=e.recruit();assert.ok(!e.team.includes(c.id));assert.equal(e.summonReward.id,c.id);e.setModal('reveal');e.finishSummon();assert.equal(e.modal,'upgrade');assert.ok(e.upgrades[0].choices.every(card=>card.owner===c.id));const id=e.owned.at(-1);e.chooseUpgrade(0);assert.equal(Object.values(e.members[id].growth).reduce((a,b)=>a+b,0),1);assert.equal(e.upgrades.length,0);}
{const e=new Engine(()=>0);e.owned.push(15);for(const id of e.team)max(e,id);assert.deepEqual(growthOwners(e),[15]);const q=e.queueTicketGrowth();assert.equal(q.id,15);e.nextUpgrade();assert.ok(q.choices.every(c=>c.owner===15));max(e,15);assert.equal(growthOwners(e).length,0);assert.equal(e.queueTicketGrowth(),null);}
{const e=new Engine(()=>0);max(e,1);for(let i=0;i<30;i++){assert.ok(!growthOwners(e).includes(1));assert.ok(rollGrowth(e,0).every(c=>c.owner!==1));}max(e,0);const offer=rollGrowth(e,0);assert.ok(offer.every(c=>c.owner>0&&!c.supply));assert.equal(new Set(offer.map(c=>c.id)).size,3);}
{const e=new Engine();for(const id of e.team)max(e,id);const time=e.time,level=e.hero.level;e.giveXP(xpForLevel(level));assert.equal(e.hero.level,level+1);assert.equal(e.tickets,1);assert.equal(e.modal,null);assert.equal(e.upgrades.length,0);assert.ok(e.events.some(ev=>ev.type==='ticketFloat'&&ev.count===1));e.update(.02);assert.ok(e.time>time);assert.deepEqual(rollGrowth(e,0),[]);}
{const e=new Engine();e.owned=CHARS.map(c=>c.id);for(const id of e.team)max(e,id);e.giveXP(100);assert.equal(e.modal,null);assert.equal(e.upgrades.length,0,'conversion never auto-redeems');assert.equal(e.tickets,1);e.setModal('warp');assert.equal(e.useTicketGrowth(),true);assert.equal(e.tickets,0);assert.equal(e.modal,'upgrade');assert.ok(!e.team.includes(e.upgrades[0].id));assert.equal(e.useTicketGrowth(),false,'double click cannot consume another ticket');e.chooseUpgrade(0);assert.equal(e.modal,null);}
{const e=new Engine(()=>0);e.owned=CHARS.map(c=>c.id);e.pickupTicket();assert.equal(e.modal,'upgrade');assert.ok(e.team.includes(e.upgrades[0].id));const gifts=e.tickets;e.chooseUpgrade(0);e.setModal('warp');assert.ok(e.useTicketGrowth());assert.equal(e.tickets,gifts-1);e.chooseUpgrade(0);for(const id of e.owned)max(e,id);e.tickets=2;e.setModal('warp');assert.equal(e.useTicketGrowth(),false);assert.equal(e.tickets,2);e.close();e.pickupTicket();assert.equal(e.modal,null);assert.equal(e.tickets,3);}
{const e=new Engine(()=>0);e.owned.push(15);e.team=[1];max(e,1);e.members[1].growth.power=2;e.queueTicketGrowth();e.queueTicketGrowth();e.nextUpgrade();const first=e.upgrades[0];assert.equal(first.id,1);e.chooseUpgrade(first.choices.findIndex(c=>c.key==='power'));assert.equal(e.upgrades[0].id,2,'stale selected owner reroutes to an unmastered owned character');}
{const e=new Engine();e.owned.push(15);for(const id of e.team)max(e,id);assert.ok(rollGold(e).every(c=>c.owner===15&&c.gold));max(e,15);e.upgrades.push({id:0,gold:true,source:'boss',advance:true});const floor=e.trial.number;e.nextUpgrade();assert.equal(e.trial.number,floor+1);assert.equal(e.modal,null);assert.equal(e.tickets,1);}
{const e=new Engine();e.team=[1];max(e,1);e.members[1].growth.power=2;e.upgrades=[{id:1,source:'ticket'},{id:0,source:'level',level:2}];e.nextUpgrade();e.chooseUpgrade(e.upgrades[0].choices.findIndex(c=>c.key==='power'));assert.equal(e.modal,null);assert.equal(e.tickets,1,'queued hero reward converts once party becomes mastered');}
assert.equal(TRIAL_TICKET_CAP,12);
console.log('Reward pools: bench summon binding, mastery exclusion/fallback, hero conversion, inventory spending, all mastered, queued rerolls and boss advancement passed.');
